# Generated by Django 4.2.24 on 2025-10-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='AC',
            new_name='ac',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='AF',
            new_name='af',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='AR',
            new_name='ar',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='awayTeam',
            new_name='away_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='AS',
            new_name='aws',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='AY',
            new_name='ay',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='FTAG',
            new_name='ftag',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='FTHG',
            new_name='fthg',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='FTR',
            new_name='ftr',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='HC',
            new_name='hc',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='HF',
            new_name='hf',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='homeTeam',
            new_name='home_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='HR',
            new_name='hr',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='HS',
            new_name='hs',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='HST',
            new_name='hst',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='HTAG',
            new_name='htag',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='HTHG',
            new_name='hthg',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='HTR',
            new_name='htr',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='HY',
            new_name='hy',
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
