# Generated by Django 4.2.24 on 2025-10-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_rename_ac_match_ac_rename_af_match_af_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='AST',
            new_name='ast',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='away_id',
            new_name='away',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_id',
            new_name='home',
        ),
    ]
