# Generated by Django 4.2.24 on 2025-10-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_rename_ast_match_ast_rename_away_id_match_away_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEPL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Match',
            new_name='MatchLaliga',
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamLaliga',
        ),
        migrations.CreateModel(
            name='MatchEPL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('fthg', models.IntegerField()),
                ('ftag', models.IntegerField()),
                ('ftr', models.CharField(max_length=1)),
                ('hthg', models.IntegerField()),
                ('htag', models.IntegerField()),
                ('htr', models.CharField(max_length=1)),
                ('hs', models.IntegerField()),
                ('aws', models.IntegerField()),
                ('hst', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('hf', models.IntegerField()),
                ('af', models.IntegerField()),
                ('hc', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('hy', models.IntegerField()),
                ('ay', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('ar', models.IntegerField()),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='match.teamepl')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='match.teamepl')),
            ],
        ),
    ]
