# Generated by Django 4.2.24 on 2025-10-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_teamlaliga_rename_match_matchepl_rename_team_teamepl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamepl',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamlaliga',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
