# Generated by Django 4.2.24 on 2025-10-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchepl',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epl_away_matches', to='match.teamepl'),
        ),
        migrations.AlterField(
            model_name='matchepl',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epl_home_matches', to='match.teamepl'),
        ),
        migrations.AlterField(
            model_name='matchlaliga',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laliga_away_matches', to='match.teamlaliga'),
        ),
        migrations.AlterField(
            model_name='matchlaliga',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laliga_home_matches', to='match.teamlaliga'),
        ),
        migrations.CreateModel(
            name='MatchLaliga2025',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('fthg', models.IntegerField()),
                ('ftag', models.IntegerField()),
                ('hy', models.IntegerField()),
                ('ay', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('ar', models.IntegerField()),
                ('hs', models.IntegerField()),
                ('aws', models.IntegerField()),
                ('hst', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('hc', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laliga2025_away_matches', to='match.teamlaliga')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laliga2025_home_matches', to='match.teamlaliga')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEPL2025',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('fthg', models.IntegerField()),
                ('ftag', models.IntegerField()),
                ('hy', models.IntegerField()),
                ('ay', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('ar', models.IntegerField()),
                ('hs', models.IntegerField()),
                ('aws', models.IntegerField()),
                ('hst', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('hc', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epl2025_away_matches', to='match.teamlaliga')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epl2025_home_matches', to='match.teamlaliga')),
            ],
        ),
    ]
