# Generated by Django 4.2.24 on 2025-10-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_alter_matchepl_away_alter_matchepl_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamepl',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamlaliga',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
