# Generated by Django 4.2.24 on 2025-10-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_teamepl_logo_teamlaliga_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamepl',
            name='model_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamlaliga',
            name='model_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
