# Generated by Django 4.2.24 on 2025-10-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_teamepl_model_index_teamlaliga_model_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamepl',
            name='name_web',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teamlaliga',
            name='name_web',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
