# Generated by Django 4.2.24 on 2025-10-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_teamepl_name_web_teamlaliga_name_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamepl',
            name='included_in_trace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamlaliga',
            name='included_in_trace',
            field=models.BooleanField(default=False),
        ),
    ]
