# Generated by Django 4.2.24 on 2025-10-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_teamepl_included_in_trace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamepl',
            old_name='included_in_trace',
            new_name='included_in_traced',
        ),
        migrations.RenameField(
            model_name='teamlaliga',
            old_name='included_in_trace',
            new_name='included_in_traced',
        ),
    ]
