# Generated by Django 4.2.24 on 2025-10-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0012_rename_included_in_trace_teamepl_included_in_traced_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchepl2025",
            name="away",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epl2025_away_matches",
                to="match.teamepl",
            ),
        ),
        migrations.AlterField(
            model_name="matchepl2025",
            name="home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epl2025_home_matches",
                to="match.teamepl",
            ),
        ),
    ]
