# Generated by Django 3.2 on 2025-10-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('FTHG', models.IntegerField()),
                ('FTAG', models.IntegerField()),
                ('FTR', models.CharField(max_length=1)),
                ('HTHG', models.IntegerField()),
                ('HTAG', models.IntegerField()),
                ('HTR', models.CharField(max_length=1)),
                ('HS', models.IntegerField()),
                ('AS', models.IntegerField()),
                ('HST', models.IntegerField()),
                ('AST', models.IntegerField()),
                ('HF', models.IntegerField()),
                ('AF', models.IntegerField()),
                ('HC', models.IntegerField()),
                ('AC', models.IntegerField()),
                ('HY', models.IntegerField()),
                ('AY', models.IntegerField()),
                ('HR', models.IntegerField()),
                ('AR', models.IntegerField()),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='home.team')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='home.team')),
            ],
        ),
    ]
